# ============================================================
# LLM LAB PROGRAM
# ============================================================
# AIM:
# Implement different tokenization techniques for a given text
# dataset. Compare Word, Subword, Character, and Byte
# tokenization methods and analyze the number of tokens
# generated by each method.
#
# Tokenization:
# Tokenization is the process of breaking text into smaller
# units called tokens. These tokens are then processed by
# language models.
#
# Techniques implemented:
# 1. Word Tokenization
# 2. Subword Tokenization
# 3. Character Tokenization
# 4. Byte Tokenization
# ============================================================


import re

# The tokenizers library is used for subword tokenization.
# Install it using:
# pip install tokenizers

from tokenizers import Tokenizer
from tokenizers.models import WordPiece
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import WordPieceTrainer

# ============================================================
# TEXT DATASET
# ============================================================
# A small text dataset is used for demonstrating the different
# tokenization techniques.

text_dataset = [
    "Large language models understand human language.",
    "Tokenization is an important step in natural language processing.",
    "Transformers use attention mechanisms to process text.",
    "Language models learn patterns from large amounts of data."
]


# Combine all sentences into one text
text = " ".join(text_dataset)

# ============================================================
# 1. WORD TOKENIZATION
# ============================================================
# Word tokenization divides the text into complete words.
#
# Example:
# "Hello world"
#       ↓
# ["Hello", "world"]
#
# Regular expressions are used to identify words and ignore
# punctuation.

def word_tokenization(text):

    # \b represents a word boundary
    # \w+ represents one or more word characters
    return re.findall(r'\b\w+\b', text)


# Generate word tokens
word_tokens = word_tokenization(text)


# ============================================================
# 2. CHARACTER TOKENIZATION
# ============================================================
# Character tokenization divides the text into individual
# characters.
#
# Example:
# "Hello"
#    ↓
# ['H', 'e', 'l', 'l', 'o']
#
# Spaces and punctuation are also treated as characters.

def character_tokenization(text):

    return list(text)


# Generate character tokens
character_tokens = character_tokenization(text)


# ============================================================
# 3. BYTE TOKENIZATION
# ============================================================
# Byte tokenization converts the text into bytes using UTF-8
# encoding.
#
# Example:
# "A"
#  ↓
# 65
#
# Each byte is represented as an integer from 0 to 255.

def byte_tokenization(text):

    return list(text.encode('utf-8'))


# Generate byte tokens
byte_tokens = byte_tokenization(text)


# ============================================================
# 4. SUBWORD TOKENIZATION
# ============================================================
# Subword tokenization breaks words into smaller meaningful
# pieces called subwords.
#
# It is useful for handling:
# - Unknown words
# - Rare words
# - New words
# - Different word forms
#
# WordPiece is one of the subword tokenization techniques
# commonly associated with transformer-based language models.
#
# Example:
# "unwanted"
#       ↓
# ["un", "##wanted"]
#
# The exact output depends on the vocabulary learned by the
# tokenizer.


def subword_tokenization(dataset):

    # Create a WordPiece tokenizer
    tokenizer = Tokenizer(
        WordPiece(unk_token="[UNK]")
    )

    # Split input text based on whitespace before applying
    # WordPiece tokenization
    tokenizer.pre_tokenizer = Whitespace()

    # Create a trainer to learn the subword vocabulary
    trainer = WordPieceTrainer(
        vocab_size=100,
        special_tokens=["[UNK]"]
    )

    # Train the tokenizer using the given dataset
    tokenizer.train_from_iterator(
        dataset,
        trainer
    )

    # Encode the complete dataset
    encoded = tokenizer.encode(
        " ".join(dataset)
    )

    # Return the generated subword tokens
    return encoded.tokens


# Generate subword tokens
subword_tokens = subword_tokenization(text_dataset)


# ============================================================
# DISPLAY TOKENIZATION RESULTS
# ============================================================

print("\n========== TOKENIZATION RESULTS ==========\n")


# ---------------- WORD TOKENS ----------------

print("WORD TOKENS:")
print(word_tokens)

print("\nNumber of Word Tokens:",
      len(word_tokens))


# ---------------- SUBWORD TOKENS ----------------

print("\nSUBWORD TOKENS:")
print(subword_tokens)

print("\nNumber of Subword Tokens:",
      len(subword_tokens))


# ---------------- CHARACTER TOKENS ----------------

print("\nCHARACTER TOKENS:")
print(character_tokens)

print("\nNumber of Character Tokens:",
      len(character_tokens))


# ---------------- BYTE TOKENS ----------------

print("\nBYTE TOKENS:")
print(byte_tokens)

print("\nNumber of Byte Tokens:",
      len(byte_tokens))


# ============================================================
# TOKEN COUNT COMPARISON
# ============================================================
# The number of tokens generated by each technique is compared
# below.
#
# Word tokenization usually produces fewer tokens because each
# complete word is treated as one token.
#
# Character and byte tokenization generally produce more tokens
# because text is divided into smaller units.
#
# Subword tokenization provides a balance between word-level
# and character-level tokenization.

print("\n========== TOKEN COUNT COMPARISON ==========\n")

print("Word Tokens      :", len(word_tokens))
print("Subword Tokens   :", len(subword_tokens))
print("Character Tokens :", len(character_tokens))
print("Byte Tokens      :", len(byte_tokens))

# ============================================================
# ANALYSIS
# ============================================================
# The token counts can be used to compare the efficiency of
# different tokenization methods.
#
# Word Tokenization:
# - Treats complete words as tokens.
# - Produces fewer tokens.
# - May struggle with unknown or rare words.
#
# Subword Tokenization:
# - Breaks words into smaller meaningful units.
# - Handles rare and unknown words better.
# - Provides a balance between word and character tokenization.
#
# Character Tokenization:
# - Treats every character as a token.
# - Produces a large number of tokens.
# - Can represent any word but requires longer sequences.
#
# Byte Tokenization:
# - Represents text using bytes.
# - Can handle any UTF-8 text.
# - Usually produces a large number of tokens.
#
# Overall:
# Tokenization affects the number of tokens and therefore
# influences the amount of text an LLM can process within its
# context window.
# ============================================================
